import Head from 'next/head';
import { v4 as uuidv4 } from 'uuid';
import { useState } from 'react';
import {
  Input,
  Table,
  Thead,
  Tbody,
  Tr,
  Th,
  Td,
  Spinner,
  Text,
} from '@chakra-ui/react';

import { useCountry, useMostCasesCountries } from '@/utils/helpers';

import styles from '@/styles/Home.module.css';

export default function Home() {
  const [countryName, setCountryName] = useState('');

  const { countries, error } = useMostCasesCountries();
  const { country, isLoading, isError } = useCountry(countryName);

  if (error) {
    return <div>Error getting countries: {error}</div>;
  }

  if (!countries) {
    return <div>Loading countries...</div>;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Covid Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Covid Tracker!</h1>

        <p className={styles.description}>
          Top 10 countries with the most cases today
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <Table variant="striped">
              <Thead>
                <Tr>
                  <Th>Country</Th>
                  <Th isNumeric>Today Cases</Th>
                  <Th isNumeric>Today Deaths</Th>
                </Tr>
              </Thead>
              <Tbody>
                {countries.map(country => (
                  <Tr key={uuidv4()}>
                    <Td>{country.country}</Td>
                    <Td isNumeric>{country.todayCases}</Td>
                    <Td isNumeric>{country.todayDeaths}</Td>
                  </Tr>
                ))}
              </Tbody>
            </Table>
          </div>
        </div>

        <footer className={styles.footer}>
          <form>
            <Text fontSize="xl">Results by country</Text>
            <Input
              placeholder="USA"
              type="text"
              name="country"
              id="country"
              value={countryName}
              onChange={evt => setCountryName(evt.target.value)}
            />
          </form>
          {isLoading ? (
            <div
              style={{ width: 600, display: 'flex', justifyContent: 'center' }}
            >
              <Spinner
                thickness="4px"
                speed="0.65s"
                emptyColor="gray.200"
                color="blue.500"
                size="lg"
              />
            </div>
          ) : (
            <div style={{ opacity: country ? 1 : 0, marginLeft: 25 }}>
              <table className={styles.table}>
                <thead>
                  <tr>
                    <th>Active</th>
                    <th>Cases</th>
                    <th>Deaths</th>
                    <th>Cases Per Million</th>
                    <th>Today Cases</th>
                    <th>Today Deaths</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>{country?.active}</td>
                    <td>{country?.cases}</td>
                    <td>{country?.deaths}</td>
                    <td>{country?.casesPerOneMillion}</td>
                    <td>{country?.todayCases}</td>
                    <td>{country?.todayDeaths}</td>
                  </tr>
                </tbody>
              </table>
            </div>
          )}
        </footer>
      </main>
    </div>
  );
}
